/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.live106.message.CLogin');
goog.provide('proto.com.live106.message.CLogin.Types');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.live106.message.CLogin = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.live106.message.CLogin, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.live106.message.CLogin.displayName = 'proto.com.live106.message.CLogin';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.live106.message.CLogin.prototype.toObject = function(opt_includeInstance) {
  return proto.com.live106.message.CLogin.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.live106.message.CLogin} msg The msg instance to transform.
 * @return {!Object}
 */
proto.com.live106.message.CLogin.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: msg.getUsername(),
    password: msg.getPassword(),
    mid: msg.getMid()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.com.live106.message.CLogin} The clone.
 */
proto.com.live106.message.CLogin.prototype.cloneMessage = function() {
  return /** @type {!proto.com.live106.message.CLogin} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.com.live106.message.CLogin.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.com.live106.message.CLogin.prototype.setUsername = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string password = 10;
 * @return {string}
 */
proto.com.live106.message.CLogin.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 10, ""));
};


/** @param {string} value  */
proto.com.live106.message.CLogin.prototype.setPassword = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional string mid = 15;
 * @return {string}
 */
proto.com.live106.message.CLogin.prototype.getMid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 15, ""));
};


/** @param {string} value  */
proto.com.live106.message.CLogin.prototype.setMid = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * @enum {number}
 */
proto.com.live106.message.CLogin.Types = {
  NORMAL: 0,
  MID: 10
};

