/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.live106.message.Protocol');

goog.require('jspb.Message');
goog.require('proto.com.live106.message.CLogin');
goog.require('proto.com.live106.message.CLogout');
goog.require('proto.com.live106.message.SLogin');
goog.require('proto.com.live106.message.SLogout');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.live106.message.Protocol = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.live106.message.Protocol, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.live106.message.Protocol.displayName = 'proto.com.live106.message.Protocol';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.live106.message.Protocol.prototype.toObject = function(opt_includeInstance) {
  return proto.com.live106.message.Protocol.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.live106.message.Protocol} msg The msg instance to transform.
 * @return {!Object}
 */
proto.com.live106.message.Protocol.toObject = function(includeInstance, msg) {
  var f, obj = {
    clogin: (f = msg.getClogin()) && proto.com.live106.message.CLogin.toObject(includeInstance, f),
    slogin: (f = msg.getSlogin()) && proto.com.live106.message.SLogin.toObject(includeInstance, f),
    clogout: (f = msg.getClogout()) && proto.com.live106.message.CLogout.toObject(includeInstance, f),
    slogout: (f = msg.getSlogout()) && proto.com.live106.message.SLogout.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.com.live106.message.Protocol} The clone.
 */
proto.com.live106.message.Protocol.prototype.cloneMessage = function() {
  return /** @type {!proto.com.live106.message.Protocol} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional CLogin cLogin = 10;
 * @return {proto.com.live106.message.CLogin}
 */
proto.com.live106.message.Protocol.prototype.getClogin = function() {
  return /** @type{proto.com.live106.message.CLogin} */ (
    jspb.Message.getWrapperField(this, proto.com.live106.message.CLogin, 10));
};


/** @param {proto.com.live106.message.CLogin|undefined} value  */
proto.com.live106.message.Protocol.prototype.setClogin = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.com.live106.message.Protocol.prototype.clearClogin = function() {
  this.setClogin(undefined);
};


/**
 * optional SLogin sLogin = 11;
 * @return {proto.com.live106.message.SLogin}
 */
proto.com.live106.message.Protocol.prototype.getSlogin = function() {
  return /** @type{proto.com.live106.message.SLogin} */ (
    jspb.Message.getWrapperField(this, proto.com.live106.message.SLogin, 11));
};


/** @param {proto.com.live106.message.SLogin|undefined} value  */
proto.com.live106.message.Protocol.prototype.setSlogin = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.com.live106.message.Protocol.prototype.clearSlogin = function() {
  this.setSlogin(undefined);
};


/**
 * optional CLogout cLogout = 20;
 * @return {proto.com.live106.message.CLogout}
 */
proto.com.live106.message.Protocol.prototype.getClogout = function() {
  return /** @type{proto.com.live106.message.CLogout} */ (
    jspb.Message.getWrapperField(this, proto.com.live106.message.CLogout, 20));
};


/** @param {proto.com.live106.message.CLogout|undefined} value  */
proto.com.live106.message.Protocol.prototype.setClogout = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.com.live106.message.Protocol.prototype.clearClogout = function() {
  this.setClogout(undefined);
};


/**
 * optional SLogout sLogout = 21;
 * @return {proto.com.live106.message.SLogout}
 */
proto.com.live106.message.Protocol.prototype.getSlogout = function() {
  return /** @type{proto.com.live106.message.SLogout} */ (
    jspb.Message.getWrapperField(this, proto.com.live106.message.SLogout, 21));
};


/** @param {proto.com.live106.message.SLogout|undefined} value  */
proto.com.live106.message.Protocol.prototype.setSlogout = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.com.live106.message.Protocol.prototype.clearSlogout = function() {
  this.setSlogout(undefined);
};


